-- Phase 4c: S&P 500 draft pool (default browsable universe)
-- Generated from https://raw.githubusercontent.com/datasets/s-and-p-500-companies/main/data/constituents.csv
-- 503 constituents as of generation time

create table if not exists public.draft_pool (
  symbol text primary key,
  name text not null,
  sector text not null check (
    sector in (
      'Technology',
      'Financials',
      'Healthcare',
      'Consumer Discretionary',
      'Consumer Staples',
      'Energy',
      'Industrials',
      'Materials',
      'Real Estate',
      'Utilities',
      'Communication Services'
    )
  ),
  updated_at timestamptz not null default now()
);

create index if not exists draft_pool_sector_idx on public.draft_pool (sector);
create index if not exists draft_pool_name_idx on public.draft_pool (name);

alter table public.draft_pool enable row level security;

drop policy if exists "draft_pool_read_authenticated" on public.draft_pool;
create policy "draft_pool_read_authenticated"
  on public.draft_pool
  for select
  to authenticated
  using (true);

-- Refresh seed data idempotently
truncate public.draft_pool;

insert into public.draft_pool (symbol, name, sector) values
  ('A', 'Agilent Technologies', 'Healthcare'),
  ('AAPL', 'Apple Inc.', 'Technology'),
  ('ABBV', 'AbbVie', 'Healthcare'),
  ('ABNB', 'Airbnb', 'Consumer Discretionary'),
  ('ABT', 'Abbott Laboratories', 'Healthcare'),
  ('ACGL', 'Arch Capital Group', 'Financials'),
  ('ACN', 'Accenture', 'Technology'),
  ('ADBE', 'Adobe Inc.', 'Technology'),
  ('ADI', 'Analog Devices', 'Technology'),
  ('ADM', 'Archer Daniels Midland', 'Consumer Staples'),
  ('ADP', 'Automatic Data Processing', 'Industrials'),
  ('ADSK', 'Autodesk', 'Technology'),
  ('AEE', 'Ameren', 'Utilities'),
  ('AEP', 'American Electric Power', 'Utilities'),
  ('AES', 'AES Corporation', 'Utilities'),
  ('AFL', 'Aflac', 'Financials'),
  ('AIG', 'American International Group', 'Financials'),
  ('AIZ', 'Assurant', 'Financials'),
  ('AJG', 'Arthur J. Gallagher & Co.', 'Financials'),
  ('AKAM', 'Akamai Technologies', 'Technology'),
  ('ALB', 'Albemarle Corporation', 'Materials'),
  ('ALGN', 'Align Technology', 'Healthcare'),
  ('ALL', 'Allstate', 'Financials'),
  ('ALLE', 'Allegion', 'Industrials'),
  ('AMAT', 'Applied Materials', 'Technology'),
  ('AMCR', 'Amcor', 'Materials'),
  ('AMD', 'Advanced Micro Devices', 'Technology'),
  ('AME', 'Ametek', 'Industrials'),
  ('AMGN', 'Amgen', 'Healthcare'),
  ('AMP', 'Ameriprise Financial', 'Financials'),
  ('AMT', 'American Tower', 'Real Estate'),
  ('AMZN', 'Amazon', 'Consumer Discretionary'),
  ('ANET', 'Arista Networks', 'Technology'),
  ('AON', 'Aon plc', 'Financials'),
  ('AOS', 'A. O. Smith', 'Industrials'),
  ('APA', 'APA Corporation', 'Energy'),
  ('APD', 'Air Products', 'Materials'),
  ('APH', 'Amphenol', 'Technology'),
  ('APO', 'Apollo Global Management', 'Financials'),
  ('APP', 'AppLovin', 'Technology'),
  ('APTV', 'Aptiv', 'Consumer Discretionary'),
  ('ARE', 'Alexandria Real Estate Equities', 'Real Estate'),
  ('ARES', 'Ares Management', 'Financials'),
  ('ATO', 'Atmos Energy', 'Utilities'),
  ('AVB', 'AvalonBay Communities', 'Real Estate'),
  ('AVGO', 'Broadcom', 'Technology'),
  ('AVY', 'Avery Dennison', 'Materials'),
  ('AWK', 'American Water Works', 'Utilities'),
  ('AXON', 'Axon Enterprise', 'Industrials'),
  ('AXP', 'American Express', 'Financials'),
  ('AZO', 'AutoZone', 'Consumer Discretionary'),
  ('BA', 'Boeing', 'Industrials'),
  ('BAC', 'Bank of America', 'Financials'),
  ('BALL', 'Ball Corporation', 'Materials'),
  ('BAX', 'Baxter International', 'Healthcare'),
  ('BBY', 'Best Buy', 'Consumer Discretionary'),
  ('BDX', 'Becton Dickinson', 'Healthcare'),
  ('BEN', 'Franklin Resources', 'Financials'),
  ('BF.B', 'Brown–Forman', 'Consumer Staples'),
  ('BG', 'Bunge Global', 'Consumer Staples'),
  ('BIIB', 'Biogen', 'Healthcare'),
  ('BKNG', 'Booking Holdings', 'Consumer Discretionary'),
  ('BKR', 'Baker Hughes', 'Energy'),
  ('BLDR', 'Builders FirstSource', 'Industrials'),
  ('BLK', 'BlackRock', 'Financials'),
  ('BMY', 'Bristol Myers Squibb', 'Healthcare'),
  ('BNY', 'BNY Mellon', 'Financials'),
  ('BR', 'Broadridge Financial Solutions', 'Industrials'),
  ('BRK.B', 'Berkshire Hathaway', 'Financials'),
  ('BRO', 'Brown & Brown', 'Financials'),
  ('BSX', 'Boston Scientific', 'Healthcare'),
  ('BX', 'Blackstone Inc.', 'Financials'),
  ('BXP', 'BXP, Inc.', 'Real Estate'),
  ('C', 'Citigroup', 'Financials'),
  ('CAG', 'Conagra Brands', 'Consumer Staples'),
  ('CAH', 'Cardinal Health', 'Healthcare'),
  ('CARR', 'Carrier Global', 'Industrials'),
  ('CASY', 'Casey''s', 'Consumer Staples'),
  ('CAT', 'Caterpillar Inc.', 'Industrials'),
  ('CB', 'Chubb Limited', 'Financials'),
  ('CBOE', 'Cboe Global Markets', 'Financials'),
  ('CBRE', 'CBRE Group', 'Real Estate'),
  ('CCI', 'Crown Castle', 'Real Estate'),
  ('CCL', 'Carnival Corporation', 'Consumer Discretionary'),
  ('CDNS', 'Cadence Design Systems', 'Technology'),
  ('CDW', 'CDW Corporation', 'Technology'),
  ('CEG', 'Constellation Energy', 'Utilities'),
  ('CF', 'CF Industries', 'Materials'),
  ('CFG', 'Citizens Financial Group', 'Financials'),
  ('CHD', 'Church & Dwight', 'Consumer Staples'),
  ('CHRW', 'C.H. Robinson', 'Industrials'),
  ('CHTR', 'Charter Communications', 'Communication Services'),
  ('CI', 'Cigna', 'Healthcare'),
  ('CIEN', 'Ciena', 'Technology'),
  ('CINF', 'Cincinnati Financial', 'Financials'),
  ('CL', 'Colgate-Palmolive', 'Consumer Staples'),
  ('CLX', 'Clorox', 'Consumer Staples'),
  ('CMCSA', 'Comcast', 'Communication Services'),
  ('CME', 'CME Group', 'Financials'),
  ('CMG', 'Chipotle Mexican Grill', 'Consumer Discretionary'),
  ('CMI', 'Cummins', 'Industrials'),
  ('CMS', 'CMS Energy', 'Utilities'),
  ('CNC', 'Centene Corporation', 'Healthcare'),
  ('CNP', 'CenterPoint Energy', 'Utilities'),
  ('COF', 'Capital One', 'Financials'),
  ('COHR', 'Coherent Corp.', 'Technology'),
  ('COIN', 'Coinbase', 'Financials'),
  ('COO', 'Cooper Companies (The)', 'Healthcare'),
  ('COP', 'ConocoPhillips', 'Energy'),
  ('COR', 'Cencora', 'Healthcare'),
  ('COST', 'Costco', 'Consumer Staples'),
  ('CPAY', 'Corpay', 'Financials'),
  ('CPRT', 'Copart', 'Industrials'),
  ('CPT', 'Camden Property Trust', 'Real Estate'),
  ('CRH', 'CRH plc', 'Materials'),
  ('CRL', 'Charles River Laboratories', 'Healthcare'),
  ('CRM', 'Salesforce', 'Technology'),
  ('CRWD', 'CrowdStrike', 'Technology'),
  ('CSCO', 'Cisco', 'Technology'),
  ('CSGP', 'CoStar Group', 'Real Estate'),
  ('CSX', 'CSX Corporation', 'Industrials'),
  ('CTAS', 'Cintas', 'Industrials'),
  ('CTSH', 'Cognizant', 'Technology'),
  ('CTVA', 'Corteva', 'Materials'),
  ('CVNA', 'Carvana', 'Consumer Discretionary'),
  ('CVS', 'CVS Health', 'Healthcare'),
  ('CVX', 'Chevron Corporation', 'Energy'),
  ('D', 'Dominion Energy', 'Utilities'),
  ('DAL', 'Delta Air Lines', 'Industrials'),
  ('DASH', 'DoorDash', 'Consumer Discretionary'),
  ('DD', 'DuPont', 'Materials'),
  ('DDOG', 'Datadog', 'Technology'),
  ('DE', 'Deere & Company', 'Industrials'),
  ('DECK', 'Deckers Brands', 'Consumer Discretionary'),
  ('DELL', 'Dell Technologies', 'Technology'),
  ('DG', 'Dollar General', 'Consumer Staples'),
  ('DGX', 'Quest Diagnostics', 'Healthcare'),
  ('DHI', 'D. R. Horton', 'Consumer Discretionary'),
  ('DHR', 'Danaher Corporation', 'Healthcare'),
  ('DIS', 'Walt Disney Company (The)', 'Communication Services'),
  ('DLR', 'Digital Realty', 'Real Estate'),
  ('DLTR', 'Dollar Tree', 'Consumer Staples'),
  ('DOC', 'Healthpeak Properties', 'Real Estate'),
  ('DOV', 'Dover Corporation', 'Industrials'),
  ('DOW', 'Dow Inc.', 'Materials'),
  ('DPZ', 'Domino''s', 'Consumer Discretionary'),
  ('DRI', 'Darden Restaurants', 'Consumer Discretionary'),
  ('DTE', 'DTE Energy', 'Utilities'),
  ('DUK', 'Duke Energy', 'Utilities'),
  ('DVA', 'DaVita', 'Healthcare'),
  ('DVN', 'Devon Energy', 'Energy'),
  ('DXCM', 'Dexcom', 'Healthcare'),
  ('EA', 'Electronic Arts', 'Communication Services'),
  ('EBAY', 'eBay Inc.', 'Consumer Discretionary'),
  ('ECL', 'Ecolab', 'Materials'),
  ('ED', 'Consolidated Edison', 'Utilities'),
  ('EFX', 'Equifax', 'Industrials'),
  ('EG', 'Everest Group', 'Financials'),
  ('EIX', 'Edison International', 'Utilities'),
  ('EL', 'Estée Lauder Companies (The)', 'Consumer Staples'),
  ('ELV', 'Elevance Health', 'Healthcare'),
  ('EME', 'Emcor', 'Industrials'),
  ('EMR', 'Emerson Electric', 'Industrials'),
  ('EOG', 'EOG Resources', 'Energy'),
  ('EQIX', 'Equinix', 'Real Estate'),
  ('EQR', 'Equity Residential', 'Real Estate'),
  ('EQT', 'EQT Corporation', 'Energy'),
  ('ERIE', 'Erie Indemnity', 'Financials'),
  ('ES', 'Eversource Energy', 'Utilities'),
  ('ESS', 'Essex Property Trust', 'Real Estate'),
  ('ETN', 'Eaton Corporation', 'Industrials'),
  ('ETR', 'Entergy', 'Utilities'),
  ('EVRG', 'Evergy', 'Utilities'),
  ('EW', 'Edwards Lifesciences', 'Healthcare'),
  ('EXC', 'Exelon', 'Utilities'),
  ('EXE', 'Expand Energy', 'Energy'),
  ('EXPD', 'Expeditors International', 'Industrials'),
  ('EXPE', 'Expedia Group', 'Consumer Discretionary'),
  ('EXR', 'Extra Space Storage', 'Real Estate'),
  ('F', 'Ford Motor Company', 'Consumer Discretionary'),
  ('FANG', 'Diamondback Energy', 'Energy'),
  ('FAST', 'Fastenal', 'Industrials'),
  ('FCX', 'Freeport-McMoRan', 'Materials'),
  ('FDS', 'FactSet', 'Financials'),
  ('FDX', 'FedEx', 'Industrials'),
  ('FDXF', 'FedEx Freight', 'Industrials'),
  ('FE', 'FirstEnergy', 'Utilities'),
  ('FFIV', 'F5, Inc.', 'Technology'),
  ('FICO', 'Fair Isaac', 'Technology'),
  ('FIS', 'Fidelity National Information Services', 'Financials'),
  ('FISV', 'Fiserv', 'Financials'),
  ('FITB', 'Fifth Third Bancorp', 'Financials'),
  ('FIX', 'Comfort Systems USA', 'Industrials'),
  ('FLEX', 'Flex Ltd.', 'Technology'),
  ('FOX', 'Fox Corporation (Class B)', 'Communication Services'),
  ('FOXA', 'Fox Corporation (Class A)', 'Communication Services'),
  ('FRT', 'Federal Realty Investment Trust', 'Real Estate'),
  ('FSLR', 'First Solar', 'Technology'),
  ('FTNT', 'Fortinet', 'Technology'),
  ('FTV', 'Fortive', 'Industrials'),
  ('GD', 'General Dynamics', 'Industrials'),
  ('GDDY', 'GoDaddy', 'Technology'),
  ('GE', 'GE Aerospace', 'Industrials'),
  ('GEHC', 'GE HealthCare', 'Healthcare'),
  ('GEN', 'Gen Digital', 'Technology'),
  ('GEV', 'GE Vernova', 'Industrials'),
  ('GILD', 'Gilead Sciences', 'Healthcare'),
  ('GIS', 'General Mills', 'Consumer Staples'),
  ('GL', 'Globe Life', 'Financials'),
  ('GLW', 'Corning Inc.', 'Technology'),
  ('GM', 'General Motors', 'Consumer Discretionary'),
  ('GNRC', 'Generac', 'Industrials'),
  ('GOOG', 'Alphabet Inc. (Class C)', 'Communication Services'),
  ('GOOGL', 'Alphabet Inc. (Class A)', 'Communication Services'),
  ('GPC', 'Genuine Parts Company', 'Consumer Discretionary'),
  ('GPN', 'Global Payments', 'Financials'),
  ('GRMN', 'Garmin', 'Consumer Discretionary'),
  ('GS', 'Goldman Sachs', 'Financials'),
  ('GWW', 'W. W. Grainger', 'Industrials'),
  ('HAL', 'Halliburton', 'Energy'),
  ('HAS', 'Hasbro', 'Consumer Discretionary'),
  ('HBAN', 'Huntington Bancshares', 'Financials'),
  ('HCA', 'HCA Healthcare', 'Healthcare'),
  ('HD', 'Home Depot (The)', 'Consumer Discretionary'),
  ('HIG', 'Hartford (The)', 'Financials'),
  ('HII', 'Huntington Ingalls Industries', 'Industrials'),
  ('HLT', 'Hilton Worldwide', 'Consumer Discretionary'),
  ('HON', 'Honeywell', 'Industrials'),
  ('HOOD', 'Robinhood Markets', 'Financials'),
  ('HPE', 'Hewlett Packard Enterprise', 'Technology'),
  ('HPQ', 'HP Inc.', 'Technology'),
  ('HRL', 'Hormel Foods', 'Consumer Staples'),
  ('HSIC', 'Henry Schein', 'Healthcare'),
  ('HST', 'Host Hotels & Resorts', 'Real Estate'),
  ('HSY', 'Hershey Company (The)', 'Consumer Staples'),
  ('HUBB', 'Hubbell Incorporated', 'Industrials'),
  ('HUM', 'Humana', 'Healthcare'),
  ('HWM', 'Howmet Aerospace', 'Industrials'),
  ('IBKR', 'Interactive Brokers', 'Financials'),
  ('IBM', 'IBM', 'Technology'),
  ('ICE', 'Intercontinental Exchange', 'Financials'),
  ('IDXX', 'Idexx Laboratories', 'Healthcare'),
  ('IEX', 'IDEX Corporation', 'Industrials'),
  ('IFF', 'International Flavors & Fragrances', 'Materials'),
  ('INCY', 'Incyte', 'Healthcare'),
  ('INTC', 'Intel', 'Technology'),
  ('INTU', 'Intuit', 'Technology'),
  ('INVH', 'Invitation Homes', 'Real Estate'),
  ('IP', 'International Paper', 'Materials'),
  ('IQV', 'IQVIA', 'Healthcare'),
  ('IR', 'Ingersoll Rand', 'Industrials'),
  ('IRM', 'Iron Mountain', 'Real Estate'),
  ('ISRG', 'Intuitive Surgical', 'Healthcare'),
  ('IT', 'Gartner', 'Technology'),
  ('ITW', 'Illinois Tool Works', 'Industrials'),
  ('IVZ', 'Invesco', 'Financials'),
  ('J', 'Jacobs Solutions', 'Industrials'),
  ('JBHT', 'J.B. Hunt', 'Industrials'),
  ('JBL', 'Jabil', 'Technology'),
  ('JCI', 'Johnson Controls', 'Industrials'),
  ('JKHY', 'Jack Henry & Associates', 'Financials'),
  ('JNJ', 'Johnson & Johnson', 'Healthcare'),
  ('JPM', 'JPMorgan Chase', 'Financials'),
  ('KDP', 'Keurig Dr Pepper', 'Consumer Staples'),
  ('KEY', 'KeyCorp', 'Financials'),
  ('KEYS', 'Keysight Technologies', 'Technology'),
  ('KHC', 'Kraft Heinz', 'Consumer Staples'),
  ('KIM', 'Kimco Realty', 'Real Estate'),
  ('KKR', 'KKR & Co.', 'Financials'),
  ('KLAC', 'KLA Corporation', 'Technology'),
  ('KMB', 'Kimberly-Clark', 'Consumer Staples'),
  ('KMI', 'Kinder Morgan', 'Energy'),
  ('KO', 'Coca-Cola Company (The)', 'Consumer Staples'),
  ('KR', 'Kroger', 'Consumer Staples'),
  ('KVUE', 'Kenvue', 'Consumer Staples'),
  ('L', 'Loews Corporation', 'Financials'),
  ('LDOS', 'Leidos', 'Industrials'),
  ('LEN', 'Lennar', 'Consumer Discretionary'),
  ('LH', 'Labcorp', 'Healthcare'),
  ('LHX', 'L3Harris', 'Industrials'),
  ('LII', 'Lennox International', 'Industrials'),
  ('LIN', 'Linde plc', 'Materials'),
  ('LITE', 'Lumentum', 'Technology'),
  ('LLY', 'Lilly (Eli)', 'Healthcare'),
  ('LMT', 'Lockheed Martin', 'Industrials'),
  ('LNT', 'Alliant Energy', 'Utilities'),
  ('LOW', 'Lowe''s', 'Consumer Discretionary'),
  ('LRCX', 'Lam Research', 'Technology'),
  ('LULU', 'Lululemon Athletica', 'Consumer Discretionary'),
  ('LUV', 'Southwest Airlines', 'Industrials'),
  ('LVS', 'Las Vegas Sands', 'Consumer Discretionary'),
  ('LYB', 'LyondellBasell', 'Materials'),
  ('LYV', 'Live Nation Entertainment', 'Communication Services'),
  ('MA', 'Mastercard', 'Financials'),
  ('MAA', 'Mid-America Apartment Communities', 'Real Estate'),
  ('MAR', 'Marriott International', 'Consumer Discretionary'),
  ('MAS', 'Masco', 'Industrials'),
  ('MCD', 'McDonald''s', 'Consumer Discretionary'),
  ('MCHP', 'Microchip Technology', 'Technology'),
  ('MCK', 'McKesson Corporation', 'Healthcare'),
  ('MCO', 'Moody''s Corporation', 'Financials'),
  ('MDLZ', 'Mondelez International', 'Consumer Staples'),
  ('MDT', 'Medtronic', 'Healthcare'),
  ('MET', 'MetLife', 'Financials'),
  ('META', 'Meta Platforms', 'Communication Services'),
  ('MGM', 'MGM Resorts', 'Consumer Discretionary'),
  ('MKC', 'McCormick & Company', 'Consumer Staples'),
  ('MLM', 'Martin Marietta Materials', 'Materials'),
  ('MMM', '3M', 'Industrials'),
  ('MNST', 'Monster Beverage', 'Consumer Staples'),
  ('MO', 'Altria', 'Consumer Staples'),
  ('MOS', 'Mosaic Company (The)', 'Materials'),
  ('MPC', 'Marathon Petroleum', 'Energy'),
  ('MPWR', 'Monolithic Power Systems', 'Technology'),
  ('MRK', 'Merck & Co.', 'Healthcare'),
  ('MRNA', 'Moderna', 'Healthcare'),
  ('MRSH', 'Marsh McLennan', 'Financials'),
  ('MRVL', 'Marvell Technology', 'Technology'),
  ('MS', 'Morgan Stanley', 'Financials'),
  ('MSCI', 'MSCI Inc.', 'Financials'),
  ('MSFT', 'Microsoft', 'Technology'),
  ('MSI', 'Motorola Solutions', 'Technology'),
  ('MTB', 'M&T Bank', 'Financials'),
  ('MTD', 'Mettler Toledo', 'Healthcare'),
  ('MU', 'Micron Technology', 'Technology'),
  ('NCLH', 'Norwegian Cruise Line Holdings', 'Consumer Discretionary'),
  ('NDAQ', 'Nasdaq, Inc.', 'Financials'),
  ('NDSN', 'Nordson Corporation', 'Industrials'),
  ('NEE', 'NextEra Energy', 'Utilities'),
  ('NEM', 'Newmont', 'Materials'),
  ('NFLX', 'Netflix', 'Communication Services'),
  ('NI', 'NiSource', 'Utilities'),
  ('NKE', 'Nike, Inc.', 'Consumer Discretionary'),
  ('NOC', 'Northrop Grumman', 'Industrials'),
  ('NOW', 'ServiceNow', 'Technology'),
  ('NRG', 'NRG Energy', 'Utilities'),
  ('NSC', 'Norfolk Southern', 'Industrials'),
  ('NTAP', 'NetApp', 'Technology'),
  ('NTRS', 'Northern Trust', 'Financials'),
  ('NUE', 'Nucor', 'Materials'),
  ('NVDA', 'Nvidia', 'Technology'),
  ('NVR', 'NVR, Inc.', 'Consumer Discretionary'),
  ('NWS', 'News Corp (Class B)', 'Communication Services'),
  ('NWSA', 'News Corp (Class A)', 'Communication Services'),
  ('NXPI', 'NXP Semiconductors', 'Technology'),
  ('O', 'Realty Income', 'Real Estate'),
  ('ODFL', 'Old Dominion', 'Industrials'),
  ('OKE', 'Oneok', 'Energy'),
  ('OMC', 'Omnicom Group', 'Communication Services'),
  ('ON', 'ON Semiconductor', 'Technology'),
  ('ORCL', 'Oracle Corporation', 'Technology'),
  ('ORLY', 'O’Reilly Automotive', 'Consumer Discretionary'),
  ('OTIS', 'Otis Worldwide', 'Industrials'),
  ('OXY', 'Occidental Petroleum', 'Energy'),
  ('PANW', 'Palo Alto Networks', 'Technology'),
  ('PAYX', 'Paychex', 'Industrials'),
  ('PCAR', 'Paccar', 'Industrials'),
  ('PCG', 'PG&E Corporation', 'Utilities'),
  ('PEG', 'Public Service Enterprise Group', 'Utilities'),
  ('PEP', 'PepsiCo', 'Consumer Staples'),
  ('PFE', 'Pfizer', 'Healthcare'),
  ('PFG', 'Principal Financial Group', 'Financials'),
  ('PG', 'Procter & Gamble', 'Consumer Staples'),
  ('PGR', 'Progressive Corporation', 'Financials'),
  ('PH', 'Parker Hannifin', 'Industrials'),
  ('PHM', 'PulteGroup', 'Consumer Discretionary'),
  ('PKG', 'Packaging Corporation of America', 'Materials'),
  ('PLD', 'Prologis', 'Real Estate'),
  ('PLTR', 'Palantir Technologies', 'Technology'),
  ('PM', 'Philip Morris International', 'Consumer Staples'),
  ('PNC', 'PNC Financial Services', 'Financials'),
  ('PNR', 'Pentair', 'Industrials'),
  ('PNW', 'Pinnacle West Capital', 'Utilities'),
  ('PODD', 'Insulet Corporation', 'Healthcare'),
  ('PPG', 'PPG Industries', 'Materials'),
  ('PPL', 'PPL Corporation', 'Utilities'),
  ('PRU', 'Prudential Financial', 'Financials'),
  ('PSA', 'Public Storage', 'Real Estate'),
  ('PSKY', 'Paramount Skydance Corporation', 'Communication Services'),
  ('PSX', 'Phillips 66', 'Energy'),
  ('PTC', 'PTC Inc.', 'Technology'),
  ('PWR', 'Quanta Services', 'Industrials'),
  ('PYPL', 'PayPal', 'Financials'),
  ('Q', 'Qnity Electronics', 'Technology'),
  ('QCOM', 'Qualcomm', 'Technology'),
  ('RCL', 'Royal Caribbean Group', 'Consumer Discretionary'),
  ('REG', 'Regency Centers', 'Real Estate'),
  ('REGN', 'Regeneron Pharmaceuticals', 'Healthcare'),
  ('RF', 'Regions Financial Corporation', 'Financials'),
  ('RJF', 'Raymond James Financial', 'Financials'),
  ('RL', 'Ralph Lauren Corporation', 'Consumer Discretionary'),
  ('RMD', 'ResMed', 'Healthcare'),
  ('ROK', 'Rockwell Automation', 'Industrials'),
  ('ROL', 'Rollins, Inc.', 'Industrials'),
  ('ROP', 'Roper Technologies', 'Technology'),
  ('ROST', 'Ross Stores', 'Consumer Discretionary'),
  ('RSG', 'Republic Services', 'Industrials'),
  ('RTX', 'RTX Corporation', 'Industrials'),
  ('RVTY', 'Revvity', 'Healthcare'),
  ('SATS', 'EchoStar', 'Communication Services'),
  ('SBAC', 'SBA Communications', 'Real Estate'),
  ('SBUX', 'Starbucks', 'Consumer Discretionary'),
  ('SCHW', 'Charles Schwab Corporation', 'Financials'),
  ('SHW', 'Sherwin-Williams', 'Materials'),
  ('SJM', 'J.M. Smucker Company (The)', 'Consumer Staples'),
  ('SLB', 'Schlumberger', 'Energy'),
  ('SMCI', 'Supermicro', 'Technology'),
  ('SNA', 'Snap-on', 'Industrials'),
  ('SNDK', 'Sandisk', 'Technology'),
  ('SNPS', 'Synopsys', 'Technology'),
  ('SO', 'Southern Company', 'Utilities'),
  ('SOLV', 'Solventum', 'Healthcare'),
  ('SPG', 'Simon Property Group', 'Real Estate'),
  ('SPGI', 'S&P Global', 'Financials'),
  ('SRE', 'Sempra', 'Utilities'),
  ('STE', 'Steris', 'Healthcare'),
  ('STLD', 'Steel Dynamics', 'Materials'),
  ('STT', 'State Street Corporation', 'Financials'),
  ('STX', 'Seagate Technology', 'Technology'),
  ('STZ', 'Constellation Brands', 'Consumer Staples'),
  ('SW', 'Smurfit Westrock', 'Materials'),
  ('SWK', 'Stanley Black & Decker', 'Industrials'),
  ('SWKS', 'Skyworks Solutions', 'Technology'),
  ('SYF', 'Synchrony Financial', 'Financials'),
  ('SYK', 'Stryker Corporation', 'Healthcare'),
  ('SYY', 'Sysco', 'Consumer Staples'),
  ('T', 'AT&T', 'Communication Services'),
  ('TAP', 'Molson Coors Beverage Company', 'Consumer Staples'),
  ('TDG', 'TransDigm Group', 'Industrials'),
  ('TDY', 'Teledyne Technologies', 'Technology'),
  ('TECH', 'Bio-Techne', 'Healthcare'),
  ('TEL', 'TE Connectivity', 'Technology'),
  ('TER', 'Teradyne', 'Technology'),
  ('TFC', 'Truist Financial', 'Financials'),
  ('TGT', 'Target Corporation', 'Consumer Staples'),
  ('TJX', 'TJX Companies', 'Consumer Discretionary'),
  ('TKO', 'TKO Group Holdings', 'Communication Services'),
  ('TMO', 'Thermo Fisher Scientific', 'Healthcare'),
  ('TMUS', 'T-Mobile US', 'Communication Services'),
  ('TPL', 'Texas Pacific Land Corporation', 'Energy'),
  ('TPR', 'Tapestry, Inc.', 'Consumer Discretionary'),
  ('TRGP', 'Targa Resources', 'Energy'),
  ('TRMB', 'Trimble Inc.', 'Technology'),
  ('TROW', 'T. Rowe Price', 'Financials'),
  ('TRV', 'Travelers Companies (The)', 'Financials'),
  ('TSCO', 'Tractor Supply', 'Consumer Discretionary'),
  ('TSLA', 'Tesla, Inc.', 'Consumer Discretionary'),
  ('TSN', 'Tyson Foods', 'Consumer Staples'),
  ('TT', 'Trane Technologies', 'Industrials'),
  ('TTD', 'Trade Desk (The)', 'Communication Services'),
  ('TTWO', 'Take-Two Interactive', 'Communication Services'),
  ('TXN', 'Texas Instruments', 'Technology'),
  ('TXT', 'Textron', 'Industrials'),
  ('TYL', 'Tyler Technologies', 'Technology'),
  ('UAL', 'United Airlines Holdings', 'Industrials'),
  ('UBER', 'Uber', 'Industrials'),
  ('UDR', 'UDR, Inc.', 'Real Estate'),
  ('UHS', 'Universal Health Services', 'Healthcare'),
  ('ULTA', 'Ulta Beauty', 'Consumer Discretionary'),
  ('UNH', 'UnitedHealth Group', 'Healthcare'),
  ('UNP', 'Union Pacific Corporation', 'Industrials'),
  ('UPS', 'United Parcel Service', 'Industrials'),
  ('URI', 'United Rentals', 'Industrials'),
  ('USB', 'U.S. Bancorp', 'Financials'),
  ('V', 'Visa Inc.', 'Financials'),
  ('VEEV', 'Veeva Systems', 'Healthcare'),
  ('VICI', 'Vici Properties', 'Real Estate'),
  ('VLO', 'Valero Energy', 'Energy'),
  ('VLTO', 'Veralto', 'Industrials'),
  ('VMC', 'Vulcan Materials Company', 'Materials'),
  ('VRSK', 'Verisk Analytics', 'Industrials'),
  ('VRSN', 'Verisign', 'Technology'),
  ('VRT', 'Vertiv', 'Industrials'),
  ('VRTX', 'Vertex Pharmaceuticals', 'Healthcare'),
  ('VST', 'Vistra Corp.', 'Utilities'),
  ('VTR', 'Ventas', 'Real Estate'),
  ('VTRS', 'Viatris', 'Healthcare'),
  ('VZ', 'Verizon', 'Communication Services'),
  ('WAB', 'Wabtec', 'Industrials'),
  ('WAT', 'Waters Corporation', 'Healthcare'),
  ('WBD', 'Warner Bros. Discovery', 'Communication Services'),
  ('WDAY', 'Workday, Inc.', 'Technology'),
  ('WDC', 'Western Digital', 'Technology'),
  ('WEC', 'WEC Energy Group', 'Utilities'),
  ('WELL', 'Welltower', 'Real Estate'),
  ('WFC', 'Wells Fargo', 'Financials'),
  ('WM', 'Waste Management', 'Industrials'),
  ('WMB', 'Williams Companies', 'Energy'),
  ('WMT', 'Walmart', 'Consumer Staples'),
  ('WRB', 'W. R. Berkley Corporation', 'Financials'),
  ('WSM', 'Williams-Sonoma, Inc.', 'Consumer Discretionary'),
  ('WST', 'West Pharmaceutical Services', 'Healthcare'),
  ('WTW', 'Willis Towers Watson', 'Financials'),
  ('WY', 'Weyerhaeuser', 'Real Estate'),
  ('WYNN', 'Wynn Resorts', 'Consumer Discretionary'),
  ('XEL', 'Xcel Energy', 'Utilities'),
  ('XOM', 'ExxonMobil', 'Energy'),
  ('XYL', 'Xylem Inc.', 'Industrials'),
  ('XYZ', 'Block, Inc.', 'Financials'),
  ('YUM', 'Yum! Brands', 'Consumer Discretionary'),
  ('ZBH', 'Zimmer Biomet', 'Healthcare'),
  ('ZBRA', 'Zebra Technologies', 'Technology'),
  ('ZTS', 'Zoetis', 'Healthcare');
