-- Phase: Top-50 crypto draft pool (CoinGecko market cap rank)
-- Generated by scripts/generate-crypto-pool-sql.mjs on 2026-06-22T20:04:42.958Z
-- Re-run: npm run generate:crypto-pool

create table if not exists public.crypto_pool (
  symbol text primary key,
  name text not null,
  coingecko_id text not null unique,
  market_cap_rank int not null check (market_cap_rank >= 1),
  reference_price_usd numeric,
  updated_at timestamptz not null default now()
);

create index if not exists crypto_pool_rank_idx on public.crypto_pool (market_cap_rank);

alter table public.crypto_pool enable row level security;

drop policy if exists "crypto_pool_read_authenticated" on public.crypto_pool;
create policy "crypto_pool_read_authenticated"
  on public.crypto_pool
  for select
  to authenticated
  using (true);

drop policy if exists "crypto_pool_service_write" on public.crypto_pool;
create policy "crypto_pool_service_write"
  on public.crypto_pool
  for all
  to service_role
  using (true)
  with check (true);

truncate public.crypto_pool;

insert into public.crypto_pool (symbol, name, coingecko_id, market_cap_rank, reference_price_usd)
values
  ('BTC', 'Bitcoin', 'bitcoin', 1, 64504),
  ('ETH', 'Ethereum', 'ethereum', 2, 1735.34),
  ('BNB', 'BNB', 'binancecoin', 4, 591.96),
  ('XRP', 'XRP', 'ripple', 6, 1.13),
  ('SOL', 'Solana', 'solana', 7, 72.79),
  ('TRX', 'TRON', 'tron', 8, 0.332022),
  ('HYPE', 'Hyperliquid', 'hyperliquid', 10, 67.51),
  ('DOGE', 'Dogecoin', 'dogecoin', 11, 0.082781),
  ('RAIN', 'Rain', 'rain', 13, 0.01608406),
  ('LEO', 'LEO Token', 'leo-token', 14, 9.48),
  ('ZEC', 'Zcash', 'zcash', 15, 449.58),
  ('XLM', 'Stellar', 'stellar', 16, 0.204511),
  ('XMR', 'Monero', 'monero', 17, 332.52),
  ('WBT', 'WhiteBIT Coin', 'whitebit', 18, 52.55),
  ('LINK', 'Chainlink', 'chainlink', 19, 7.92),
  ('ADA', 'Cardano', 'cardano', 20, 0.159051),
  ('CC', 'Canton', 'canton-network', 21, 0.150068),
  ('LAB', 'LAB', 'lab', 22, 16.82),
  ('GRAM', 'Gram (prev. Toncoin)', 'the-open-network', 25, 1.7),
  ('BCH', 'Bitcoin Cash', 'bitcoin-cash', 27, 198.77),
  ('M', 'MemeCore', 'memecore', 28, 2.94),
  ('LTC', 'Litecoin', 'litecoin', 29, 44.62),
  ('HBAR', 'Hedera', 'hedera-hashgraph', 30, 0.07919),
  ('SUI', 'Sui', 'sui', 32, 0.720899),
  ('SHIB', 'Shiba Inu', 'shiba-inu', 34, 0.00000467),
  ('NEAR', 'NEAR Protocol', 'near', 35, 2.11),
  ('CRO', 'Cronos', 'crypto-com-chain', 37, 0.058846),
  ('AVAX', 'Avalanche', 'avalanche-2', 38, 6.27),
  ('TAO', 'Bittensor', 'bittensor', 41, 231.84),
  ('WLD', 'Worldcoin', 'worldcoin-wld', 42, 0.625443),
  ('UNI', 'Uniswap', 'uniswap', 45, 3.02),
  ('WLFI', 'World Liberty Financial', 'world-liberty-financial', 46, 0.058337),
  ('MNT', 'Mantle', 'mantle', 47, 0.534206),
  ('OKB', 'OKB', 'okb', 48, 80.83),
  ('ASTER', 'Aster', 'aster-2', 49, 0.633981),
  ('ONDO', 'Ondo', 'ondo-finance', 51, 0.330962),
  ('DOT', 'Polkadot', 'polkadot', 52, 0.9452),
  ('HTX', 'HTX DAO', 'htx-dao', 53, 0.00000175),
  ('PI', 'Pi Network', 'pi-network', 55, 0.135256),
  ('SKY', 'Sky', 'sky', 56, 0.059084),
  ('ICP', 'Internet Computer', 'internet-computer', 59, 2.25),
  ('BGB', 'Bitget Token', 'bitget-token', 60, 1.76),
  ('PEPE', 'Pepe', 'pepe', 61, 0.00000282),
  ('MORPHO', 'Morpho', 'morpho', 62, 1.79),
  ('AAVE', 'Aave', 'aave', 63, 75.38),
  ('ETC', 'Ethereum Classic', 'ethereum-classic', 64, 7.25),
  ('QNT', 'Quant', 'quant-network', 65, 69.85),
  ('U', 'United Stables', 'united-stables', 66, 0.999899),
  ('KCS', 'KuCoin', 'kucoin-shares', 69, 7.24),
  ('ATOM', 'Cosmos Hub', 'cosmos', 71, 1.79)
on conflict (symbol) do update
  set name = excluded.name,
      coingecko_id = excluded.coingecko_id,
      market_cap_rank = excluded.market_cap_rank,
      reference_price_usd = excluded.reference_price_usd,
      updated_at = now();
